import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" >
      <body className="scroll-smooth overflow-x-hidden" cz-shortcut-listen="true">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
